version: "2"
services:
    client:
        image: gf-client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./gf-client:/client
            - /gf-client/node_modules
        links:
            - api
        networks:
            - gfnetwork
    api:
        image: gf-api
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./api:../api
            - /api/node_modules
        depends_on:
            - mongodb
        networks:
            - gfnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - gfnetwork
networks:
    gfnetwork:
        driver: bridge